Test roading CSV

In [2]:
import pandas as pd

df = pd.read_csv("output_test.csv")

In [3]:
df

,country,job_title,company_name,company_url,location,benefit,posted,company_description,job_url,job_description
0,spain,Machine Learning Engineer - LiveOps Automation,Scopely,https://www.linkedin.com/company/scopely?trk=p...,Spain,NaN,NaN,Scopely is looking for a\nMachine Learning Eng...,https://es.linkedin.com/jobs/view/machine-lear...,Scopely is looking for a\nMachine Learning Eng...
1,spain,Software Engineer (Frontend),Revolut,https://uk.linkedin.com/company/revolut?trk=pu...,Spain,NaN,NaN,About Revolut\nPeople deserve more from their ...,https://es.linkedin.com/jobs/view/software-eng...,About Revolut\nPeople deserve more from their ...
2,spain,"Software Engineer, Integrations",Topsort,https://www.linkedin.com/company/topsort?trk=p...,Spain,Be an early applicant,NaN,We're quickly growing and super excited for yo...,https://es.linkedin.com/jobs/view/software-eng...,We're quickly growing and super excited for yo...
3,spain,Video Game Specialist - Freelance AI Trainer P...,"Meridial Marketplace, by Invisible",https://www.linkedin.com/company/meridial-mark...,Spain,NaN,NaN,Are you an experienced PC gamer eager to help ...,https://es.linkedin.com/jobs/view/video-game-s...,Are you an experienced PC gamer eager to help ...
4,spain,QA Engineer,Logicalis Spain,https://es.linkedin.com/company/logicalis-spai...,"Barcelona, Catalonia, Spain",Be an early applicant,NaN,En Logicalis Spain buscamos un/a\nQA Engineer\...,https://es.linkedin.com/jobs/view/qa-engineer-...,En Logicalis Spain buscamos un/a\nQA Engineer\...
5,spain,Desarrollador/a RPG (Remoto),Katatek Group,https://es.linkedin.com/company/katatek-group?...,Spain,NaN,NaN,Seguimos creciendo y buscamos un/a Desarrollad...,https://es.linkedin.com/jobs/view/desarrollado...,Seguimos creciendo y buscamos un/a Desarrollad...
6,spain,Junior Data Analyst,Evolve,https://es.linkedin.com/school/evolve-es/?trk=...,Spain,Be an early applicant,NaN,Descripción de la oferta\nEn nuestro Programa ...,https://es.linkedin.com/jobs/view/junior-data-...,Descripción de la oferta\nEn nuestro Programa ...
7,spain,Data Analyst (Remote),Constructor,https://www.linkedin.com/company/constructor-i...,Spain,Be an early applicant,NaN,About Us\nConstructor is the next-generation p...,https://es.linkedin.com/jobs/view/data-analyst...,About Us\nConstructor is the next-generation p...
8,spain,"UX Research Analyst (Spain, remote)",TransPerfect,https://www.linkedin.com/company/transperfect?...,"Barcelona, Catalonia, Spain",Be an early applicant,NaN,Work Location\n: Spain (Remote)\nWork Schedule...,https://es.linkedin.com/jobs/view/ux-research-...,Work Location\n: Spain (Remote)\nWork Schedule...
9,spain,Software Engineer - Data Infrastructure - Kafka,Canonical,https://uk.linkedin.com/company/canonical?trk=...,"Valencia, Valencian Community, Spain",Be an early applicant,NaN,Canonical is building a comprehensive automati...,https://es.linkedin.com/jobs/view/software-eng...,Canonical is building a comprehensive automati...
10,spain,Software Engineer - Data Infrastructure - Kafka,Canonical,https://uk.linkedin.com/company/canonical?trk=...,"Salamanca, Castilla and Leon, Spain",Be an early applicant,NaN,Canonical is building a comprehensive automati...,https://es.linkedin.com/jobs/view/software-eng...,Canonical is building a comprehensive automati...
11,spain,"UX Research Analyst (Spain, remote)",TransPerfect,https://www.linkedin.com/company/transperfect?...,Spain,Be an early applicant,NaN,Work Location\n: Spain (Remote)\nWork Schedule...,https://es.linkedin.com/jobs/view/ux-research-...,Work Location\n: Spain (Remote)\nWork Schedule...

Functions

In [ ]:
#text cleaning function 
import re

def clean_text_column(df):
    def clean_text(text):
        text = re.sub(r"\s+", " ", str(text))          # remove newlines & extra spaces
        text = re.sub(r"[^\w\s\-\/]", "", text)       # remove special characters/emojis
        return text.strip()
    
    return df.apply(clean_text)

In [19]:
#deletes the URLs as this is not needed for the EDA 
def drop_url_columns(df):
    df = df.copy()
    
    columns_to_drop = ["job_url", "company_url"]
    
    # Only drop if they exist (prevents errors)
    df = df.drop(columns=[col for col in columns_to_drop if col in df.columns])
    
    return df

In [25]:
def prepare_for_eda(df):
    df = df.copy()
    
    columns_to_drop = ["job_url", "company_url", "benefit", "country"]
    
    # Drop only columns that exist (safe)
    df = df.drop(columns=[col for col in columns_to_drop if col in df.columns])
    
    # Standardize column names
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )
    
    return df

EDA data analyst Jonior

In [5]:
data_analyst_j = pd.read_csv("analyst_jun.csv")

In [15]:
data_analyst_j

,country,job_title,company_name,company_url,location,benefit,posted,company_description,job_url,job_description
0,spain,🚀📊 Científico/a de Datos (Data Scientist) (Cie...,Quental,https://es.linkedin.com/company/quental?trk=pu...,"Barcelona, Catalonia, Spain",NaN,2 weeks ago,¿Te gustaría participar en un gran proyecto de...,https://es.linkedin.com/jobs/view/%F0%9F%9A%80...,¿Te gustaría participar en un gran proyecto de...
1,spain,Data Scientist,Sabadell Consumer Finance,https://es.linkedin.com/company/sabadellconsum...,"Sant Cugat del Vallès, Catalonia, Spain",NaN,1 day ago,¿Qué estamos buscando?\nActualmente nos encont...,https://es.linkedin.com/jobs/view/data-scienti...,¿Qué estamos buscando?\nActualmente nos encont...
2,spain,Data Scientist,"Linde Material Handling Iberica, SA",https://es.linkedin.com/company/linde-material...,"Barcelona, Catalonia, Spain",NaN,2 weeks ago,Linde Material Handling is among the world lea...,https://es.linkedin.com/jobs/view/data-scienti...,Linde Material Handling is among the world lea...
3,spain,Data Scientist - 100% Teletrabajo,Nunegal Consulting,https://es.linkedin.com/company/nunegal?trk=pu...,Spain,NaN,1 week ago,¿Tienes experiencia como Data Scientist? ¿Te i...,https://es.linkedin.com/jobs/view/data-scienti...,¿Tienes experiencia como Data Scientist? ¿Te i...
4,spain,MACHINE LEARNING ENGINEER / DATA ENGINEER,TENDAM,https://es.linkedin.com/company/tendam?trk=pub...,Greater Madrid Metropolitan Area,NaN,2 weeks ago,MACHINE LEARNING ENGINEER / DATA ENGINEER\nAt ...,https://es.linkedin.com/jobs/view/machine-lear...,MACHINE LEARNING ENGINEER / DATA ENGINEER\nAt ...
...,...,...,...,...,...,...,...,...,...,...
65,spain,Únete A Un Equipo Dinámico: Envía Tu Cv,Grupo Vihotec,https://es.linkedin.com/company/grupovihotec?t...,"Murcia, Región de Murcia, Spain",NaN,1 week ago,Ubicación: Varias ubicaciones disponibles\nJor...,https://es.linkedin.com/jobs/view/%C3%BAnete-a...,Ubicación: Varias ubicaciones disponibles\nJor...
66,spain,JOIN US COMUNIDAD VALENCIANA,The Fitzgerald Burger Company,https://www.linkedin.com/company/the-fitzgeral...,"Torrent, Valencian Community, Spain",Be an early applicant,NaN,Descripción\nEn The Fitzgerald nos flipa dar e...,https://es.linkedin.com/jobs/view/join-us-comu...,Descripción\nEn The Fitzgerald nos flipa dar e...
67,spain,Entrenador,DeGood,https://www.linkedin.com/company/degood?trk=pu...,"Granada, Andalusia, Spain",Be an early applicant,5 days ago,"Entrenar bien es, sobre todo, rodearse bien.En...",https://es.linkedin.com/jobs/view/entrenador-a...,"Entrenar bien es, sobre todo, rodearse bien.En..."
68,spain,"Mozos De Carga Y Descarga, Almacén Y/O Mercado...",Ferrocarrils Generalitat Valenciana,https://es.linkedin.com/company/ferrocarrilsge...,"Alicante, Valencian Community, Spain",NaN,3 days ago,REQUISITOS:PERSONA JOVEN MENOR DE 30 AÑOS E IN...,https://es.linkedin.com/jobs/view/mozos-de-car...,REQUISITOS:PERSONA JOVEN MENOR DE 30 AÑOS E IN...
69,spain,🚀Data Scientist - Data & Analytics 🚀,Decskill España,https://es.linkedin.com/company/decskill-espa%...,"Madrid, Community of Madrid, Spain",Actively Hiring,1 week ago,Decskill nació en 2014 como una consultora de ...,https://es.linkedin.com/jobs/view/%F0%9F%9A%80...,Decskill nació en 2014 como una consultora de ...

In [14]:
clean_text_column(data_analyst_j)

country                0 spain 1 spain 2 spain 3 spain 4 spain  65 sp...
job_title              0  Científico/a de Datos Data Scientist Cie 1 ...
company_name           0 Quental 1 Sabadell Consumer Finance 2 Linde ...
company_url            0 https//eslinkedincom/company/quentaltrkpu 1 ...
location               0 Barcelona Catalonia Spain 1 Sant Cugat del V...
benefit                0 NaN 1 NaN 2 NaN 3 NaN 4 NaN  65 NaN 66 Be an...
posted                 0 2 weeks ago 1 1 day ago 2 2 weeks ago 3 1 we...
company_description    0 Te gustaría participar en un gran proyecto d...
job_url                0 https//eslinkedincom/jobs/view/F09F9A80 1 ht...
job_description        0 Te gustaría participar en un gran proyecto d...
dtype: str

In [20]:
drop_url_columns(data_analyst_j)

,country,job_title,company_name,location,benefit,posted,company_description,job_description
0,spain,Científico/a de Datos Data Scientist Científic...,Quental,"Barcelona, Catalonia, Spain",NaN,2 weeks ago,¿Te gustaría participar en un gran proyecto de...,¿Te gustaría participar en un gran proyecto de...
1,spain,Data Scientist,Sabadell Consumer Finance,"Sant Cugat del Vallès, Catalonia, Spain",NaN,1 day ago,¿Qué estamos buscando?\nActualmente nos encont...,¿Qué estamos buscando?\nActualmente nos encont...
2,spain,Data Scientist,"Linde Material Handling Iberica, SA","Barcelona, Catalonia, Spain",NaN,2 weeks ago,Linde Material Handling is among the world lea...,Linde Material Handling is among the world lea...
3,spain,Data Scientist - 100 Teletrabajo,Nunegal Consulting,Spain,NaN,1 week ago,¿Tienes experiencia como Data Scientist? ¿Te i...,¿Tienes experiencia como Data Scientist? ¿Te i...
4,spain,MACHINE LEARNING ENGINEER / DATA ENGINEER,TENDAM,Greater Madrid Metropolitan Area,NaN,2 weeks ago,MACHINE LEARNING ENGINEER / DATA ENGINEER\nAt ...,MACHINE LEARNING ENGINEER / DATA ENGINEER\nAt ...
...,...,...,...,...,...,...,...,...
65,spain,Únete A Un Equipo Dinámico Envía Tu Cv,Grupo Vihotec,"Murcia, Región de Murcia, Spain",NaN,1 week ago,Ubicación: Varias ubicaciones disponibles\nJor...,Ubicación: Varias ubicaciones disponibles\nJor...
66,spain,JOIN US COMUNIDAD VALENCIANA,The Fitzgerald Burger Company,"Torrent, Valencian Community, Spain",Be an early applicant,NaN,Descripción\nEn The Fitzgerald nos flipa dar e...,Descripción\nEn The Fitzgerald nos flipa dar e...
67,spain,Entrenador,DeGood,"Granada, Andalusia, Spain",Be an early applicant,5 days ago,"Entrenar bien es, sobre todo, rodearse bien.En...","Entrenar bien es, sobre todo, rodearse bien.En..."
68,spain,Mozos De Carga Y Descarga Almacén Y/O Mercado ...,Ferrocarrils Generalitat Valenciana,"Alicante, Valencian Community, Spain",NaN,3 days ago,REQUISITOS:PERSONA JOVEN MENOR DE 30 AÑOS E IN...,REQUISITOS:PERSONA JOVEN MENOR DE 30 AÑOS E IN...
69,spain,Data Scientist - Data Analytics,Decskill España,"Madrid, Community of Madrid, Spain",Actively Hiring,1 week ago,Decskill nació en 2014 como una consultora de ...,Decskill nació en 2014 como una consultora de ...

In [22]:
data_analyst_j["benefit"].unique()

<StringArray>
[nan, 'Be an early applicant', 'Actively Hiring']
Length: 3, dtype: str

In [26]:
prepare_for_eda(data_analyst_j)

,job_title,company_name,location,posted,company_description,job_description
0,Científico/a de Datos Data Scientist Científic...,Quental,"Barcelona, Catalonia, Spain",2 weeks ago,¿Te gustaría participar en un gran proyecto de...,¿Te gustaría participar en un gran proyecto de...
1,Data Scientist,Sabadell Consumer Finance,"Sant Cugat del Vallès, Catalonia, Spain",1 day ago,¿Qué estamos buscando?\nActualmente nos encont...,¿Qué estamos buscando?\nActualmente nos encont...
2,Data Scientist,"Linde Material Handling Iberica, SA","Barcelona, Catalonia, Spain",2 weeks ago,Linde Material Handling is among the world lea...,Linde Material Handling is among the world lea...
3,Data Scientist - 100 Teletrabajo,Nunegal Consulting,Spain,1 week ago,¿Tienes experiencia como Data Scientist? ¿Te i...,¿Tienes experiencia como Data Scientist? ¿Te i...
4,MACHINE LEARNING ENGINEER / DATA ENGINEER,TENDAM,Greater Madrid Metropolitan Area,2 weeks ago,MACHINE LEARNING ENGINEER / DATA ENGINEER\nAt ...,MACHINE LEARNING ENGINEER / DATA ENGINEER\nAt ...
...,...,...,...,...,...,...
65,Únete A Un Equipo Dinámico Envía Tu Cv,Grupo Vihotec,"Murcia, Región de Murcia, Spain",1 week ago,Ubicación: Varias ubicaciones disponibles\nJor...,Ubicación: Varias ubicaciones disponibles\nJor...
66,JOIN US COMUNIDAD VALENCIANA,The Fitzgerald Burger Company,"Torrent, Valencian Community, Spain",NaN,Descripción\nEn The Fitzgerald nos flipa dar e...,Descripción\nEn The Fitzgerald nos flipa dar e...
67,Entrenador,DeGood,"Granada, Andalusia, Spain",5 days ago,"Entrenar bien es, sobre todo, rodearse bien.En...","Entrenar bien es, sobre todo, rodearse bien.En..."
68,Mozos De Carga Y Descarga Almacén Y/O Mercado ...,Ferrocarrils Generalitat Valenciana,"Alicante, Valencian Community, Spain",3 days ago,REQUISITOS:PERSONA JOVEN MENOR DE 30 AÑOS E IN...,REQUISITOS:PERSONA JOVEN MENOR DE 30 AÑOS E IN...
69,Data Scientist - Data Analytics,Decskill España,"Madrid, Community of Madrid, Spain",1 week ago,Decskill nació en 2014 como una consultora de ...,Decskill nació en 2014 como una consultora de ...